### ISSUE TITLE
SDK causes prod build errors in Next 13

### ISSUE THREAD

**Issue by jiyuu-jin** [valist-io/valist-js#391]
### What package has an issue

@valist/sdk

### Describe the bug

<img width="1223" alt="image" src="https://github.com/valist-io/valist-js/assets/19313806/206dba60-5d34-4770-a876-931660622e19">

### What version of the package do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by red-game-dev** [comment]
Seems this issue happens even when the compiled SDK. I tried to use `verifyValistToken(SECRET, API_KEY)` and seems it happens. While in HyperPlay-dev we've got the following code, doesn't seem it does any change to this

```typescript
    config.plugins.push(new options.webpack.NormalModuleReplacementPlugin(/node:/, (resource) => {
      resource.request = resource.request.replace(/^node:/, "");
    }));
```

Image below while I call an endpoint that I need to use `verifyValistToken` method
![image](https://github.com/valist-io/valist-js/assets/75917402/ceee28a5-af26-4b06-8753-3f3b1398b804)

**Comment by awantoch** [comment]
fixed via: https://github.com/valist-io/hyperplay-dev/pull/136/files#diff-882b2c04b01b2e8b2cdcf1817c30ea503a8005f1c0d54cfff37053b6801fea85R36
